### PR TITLE
dummy package

### PR DESCRIPTION
**Pull request by 2bndy5**
this sets up
- readme
- docs (added my custom "darkness.css" to make the readthedocs sphinx theme use dark mode 😃 )
- license
- package structure
- setup.py file
- workflows for building docs and uploading to pypi upon release

## Important
The release.yml workflow assumes this repo's settings have a "secret" key named `pypi_token` that contains the API token for the pypi account used to upload. [According to pypi](https://pypi.org/help#apitoken), this API token is prefixed with `pypi-` (inclusive to secret key).

### About Authors metdata
I've taken the liberty of adding everyone (including email if publicly available on github) that contributed to the various pyRF24*.cpp files. Although, I can reduce this info to only nRF24 org maintainers or the pypi account's email. I don't think the emails are required for pypi, but they're there for transparency.

p.s. The docs aren't setup to be deployed (intentionally), but they do build correctly if you follow the readme instructions at the bottom.

### CODE REVIEW

**Comment by TMRh20** [comment]
Please excuse my ignorance, but I'm a bit confused. 
First I guess, this all looks good, but how do I verify it works etc?
Second is what do you need me to do to set this up properly? I assume you need me or Avamander to set up the API key etc?

**Comment by 2bndy5** [comment]
>I assume you need me or Avamander to set up the API key etc?

Yes. The API key is gotten from the pypi account's settings. The pyRF24 repo should have this key saved as "pypi_token" in the settings' "secret" section.

Sample screenshot:


If you named the "secret" key something else, I can rename the `secrets.pypi_token` reference in release.yml to whatever name you picked.

>Please excuse my ignorance

No worries. No need to rush.

**Comment by TMRh20** [comment]
Ok, thanks for the info, that should help
According to https://pypi.org/help/#apitoken I assumed it should be named `__TOKEN__` 
The password has the `pypy-` prefix

**Comment by 2bndy5** [comment]
ok I just tested the api token mechanism with my pypi account that now has 2FA enabled, and it worked fine.

Side note, I chose to generate a different api token for both repos I have setup to release to pypi (I made a lib for those circular trackpads found in Steam-HTC VR controllers & the Steam Controller gamepad 🤓 ). I imagine an API token for the entire pypi account (1 that's used for multiple repos) would work the same.

Ready to merge & release v0.0 when you are. Ping me if there are any problems.

**Comment by TMRh20** [comment]
Just some minor issues, not sure how far  this should be set up, but figure I can complain now and fix later:
1. With sphinx I had to run apt-get install instead of using pip: https://stackoverflow.com/questions/37757151/the-sphinx-build-command-was-not-found
2. At the bottom of readme.rst, it should be changed from `sphinx build...` to `sphinx-build -E -W . _build`
3. In readme.rst I had to change all the code-block statements to say "bash"  .. code-block:: bash

**Comment by 2bndy5** [comment]
when you see "sphinx-build command not found" it usually means the python's script folder isn't in your PATH env var. This is not a default addition upon python installation/update ☹️ 

Because I'm developing from Windows my PATH env var contains `/mnt/c/Users/ytreh/AppData/Roaming/Python/Python38/Scripts` when I checked it with `echo $PATH` (using WSL Ubuntu bash). 

The `sphinx-quickstart` cmd that I used to set it up generated a makefile and make.bat files, but I removed them thinking they were specific to my machine. I could restore them from my recycling bin, and see if that helps.

using bash syntax is cool because COLORS! No complaints there.

Either way, you're right the building docs instructions will need some attention.

**Comment by 2bndy5** [comment]
I take that back. The generated Makefile works but it allows errors to get rendered into the docs 👎 
I can't get the `./make html -W` to work. 
I guess its worth just adding a paragraph about the "sphinx-build command not found" in the readme.

**Pull request merged**
