### PR TITLE
using submodules of pybind11 and RF24* repos

### LINKED ISSUE #1: PEP8 compliance for pyRF24 package
I started talking about the pyRF24 examples in relation to poor formatting (mostly readability) in nRF24/RF24#391, but that quickly got off topic. This issue will be my home for updating pyRF24 package as I have some concerns:

1. The name `pyRF24` is ok as a folder name, but pypi.org expects package names to be all lowercase using `-` as word delimiters. Furthermore, after installing of pyRF24, the wrapper is registered under the package name RF24 -- this is not ok. Package names should be as descriptive as possible and use the same convention pypi.org expects, except `_` in place of `-` since `-` would be interpreted as a subtraction in python import statements. Not to mention the RF24 package can be confused with the RF24 class especially for namespace-ing reasons. On that note, `from RF24 import *` is discouraged as risky. Tagging nRF24/RF24#589 as this issue progresses that one.
2. The API for C++ does not conform to [PEP8 standards](https://www.python.org/dev/peps/pep-0008/). There are a few required changes to make it so:
    - [x] Function, attribute, parameter, and module names should follow snake-casing convention. Class names are camel-casing. Constants should be in all caps using `_` as word delimiters. Currently pyRF24's classes & constants are PEP8 compliant. Technically the module names don't apply to pyRF24 because of the nature of wrapping C++. Function, parameter, & attributes names can be changed due to the nature of wrapping C++ with libboost-python. See [PEP8 Naming Convention guidelines](https://www.python.org/dev/peps/pep-0008/#naming-conventions).
    - [x] Python decorated attributes aren't really being taken advantage of in pyRF24. With the use of python's builtin decorators, setters and getters should be consolidated into decorated attributes. This is because python does not protect against user access to private members, thus the naming convention for "magic functions"  (e.g. `__repr__()`) and private members (e.g. `_private_member`). However, libboost-python abstracts the "magic methods" for us, and Arduino convention recommends the same prefix for private members. This one isn't listed as part of the PEP8 convention, but it is a VERY COMMON practice in python.
    - [x] [Whitespace ](https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements)and [line length ](https://www.python.org/dev/peps/pep-0008/#maximum-line-length)can be easily addressed with the python package called black. Pylint is more user friendly as it can flag errors in VSCode as well as make suggestions about optimizing readability (e.g. using `for i, val in enumerate(my_list):` instead of `for i in range(len(my_list)):`)
    - [x]  [Docstrings ](https://www.python.org/dev/peps/pep-0008/#id33)must be included for different scopes. Module-level and function-level docstrings are the only scopes that really apply to pyRF24 (in examples). Docstrings in python are triple quoted strings of text.
    - [x] Certain keywords already defined for python should be avoided. Most important example of this that I've noticed is when creating references for parameters in the wrapper and declaring variables in the examples: The use of `len` to describe the length of a buffer; `len` in python is a builtin function that returns the length of an iterable object.
    - [x] Python packages are structured to allow multiple modules under the same namespace. The way the wrapper is written currently allows 1 module per RF24 library. Meaning pyRF24 installs as RF24 package containing a RF24 class; pyRf24Mesh installs as RF24Mesh package containing a Rf24Mesh class; pyRF24Network installs as RF24Network package containing a RF24Network class. Since these RF24* libraries' dependency is incremental (RF24 <- RF24Network <- RF24Mesh), they should be installed as 3 different modules in 1 package. This would also simplify namespacing for python coders as well.
    - [x] Python2 has reached End-of-Life as of January 2020. Debian-based distros will continue to ship with python2 only so that python2 code will still run, but python2 developers have had ample time and notice to migrate to python3. I say this because libboost-python has dropped python2 support as of v1.70 (as of this writing v1.67 is the version that `apt` will install). To address this, we only need to remove install instructions for python2 from the docs if/when python2 stops shipping with debian-based distros or if/when libboost-python v1.70 becomes the default version installed by `apt`. The [setup.py files should also be adjusted](https://github.com/nRF24/RF24/blob/d0627715a2e9ff626e7bfbb4d89215f94c9bc8cd/pyRF24/setup.py#L34-L37) at the same time.

### PR DESCRIPTION
**Pull request by 2bndy5**
This addresses #3, fixes #1 and provides python wrappers for RF24, RF24Network, & RF24Mesh libs in 1 installable package.

- Some of the underlying API is changed to better suite PEP8 standards. For example, `RF24::setAutoAck()` from C++ is `RF24.set_auto_ack()` in python.
- Other getters/setters have been reduced to pythonic attributes
   - `channel`
   - `payload_size`
   - `pa_level` (value set/get as enumeration). Note `set_pa_level()` still exists to control `lna_enabled` parameter.
   - `crc_length` (value set/get as enumeration)
   - `data_rate` (value set/get as enumeration)
   - `address_width`
   - `dynamic_payloads`
   - `ack_payloads`
   - `rpd` (read-only)
- For now, the `open_*x_pipe()` functions only accept addresses as a buffer protocol object (native python's bytes or bytearray objects). The deprecated versions of `open****ingPipe()` (which accept a uint64_t as addresses) are not supported, although this may change in the future if requested.
- I also wrote stub files (the .pyi files) for type hinting.
- All of the API can be imported from the pkg's root level. Fow example,
   ```py
   from pyrf24.rf24 import RF24, RF24_PA_LOW
   from pyrf24.rf24_network import RF24Network, MAX_PAYLOAD_SIZE
   from pyrf24.rf24_mesh import RF24Mesh, MESH_DEFAULT_ADDRESS
   ```
   is equivalent to
   ```py
   from pyrf24 import (
       RF24,
       RF24_PA_LOW,
       RF24Network,
       MAX_PAYLOAD_SIZE,
       RF24Mesh,
       MESH_DEFAULT_ADDRESS,
   )
   ```
- I also threw in a fake_ble.py module that uses the RF24 library to imitate a BLE beacon. This API is ported from the CirPy lib and is covered by the original work's MIT license. There's a fake_ble_test.py example (also ported from the CirPy lib) that demonstrates how to use it.
- Docs have been updated (including README). Instructions on how to build/install the pkg are in the README. While not officially documented it's also possible to change macros' definitions like so
   ```
   python setup.py bdist_wheel -DRF24_DEBUG=ON -DSLOW_ADDR_POLL_RESPONSE=10
   ```
   Note that RF24_DEBUG will control debugging output specifically for RF24 lib only, and SERIAL_DEBUG will control debugging output for RF24Network. All other debug macros use the same name from the underlying C++ implementation.
   - You'll notice that the pyRF24*.cpp have the docs embedded into the bindings. This means that the docs are directly extracted from an installed pyrf24 pkg. Additionally, this also allows using the python REPL's `help()` function to get more info about the API (ie `help(RF24.begin)` will show exactly what is hosted in the docs as RST syntax).

---
NOTE: Distributing this pkg for use with pip install from pypi uploads is yet another beast of an issue. I'll open another issue (see #6 ) to discuss it, but I think it will require either self-hosted CI runners (using privately owned/maintained RPi devices) or some kind of VM that emulates the RPi architecture and corresponding OS "bitness" (building 32bit [binary distributable wheels](https://www.python.org/dev/peps/pep-0427/) is a problem from 64bit host machines).

### CODE REVIEW

**Comment by TMRh20** [comment]
Having some trouble installing this following your docs at https://github.com/2bndy5/pyRF24/tree/add-submodules
As usual, its probably something I'm not understanding or doing wrong, but thought I should mention it...

1. `git clone --branch add-submodules https://github.com/2bndy5/pyRF24`
2. `cd pyRF24`
3. `python -m pip install .`

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /home/pi/pyRF24
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: pyrf24
  Building wheel for pyrf24 (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpbuow1nbx_in_process.py build_wheel /tmp/tmptqj4u52a
       cwd: /tmp/pip-req-build-nbqjuoh7
  Complete output (89 lines):
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 10.2.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 10.2.1
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-req-build-nbqjuoh7/_cmake_test_compile/build
  -- The C compiler identification is GNU 10.2.1
  -- The CXX compiler identification is GNU 10.2.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- This project is being built using scikit-build & pybind11
  CMake Error at CMakeLists.txt:10 (add_subdirectory):
    The source directory

      /tmp/pip-req-build-nbqjuoh7/pybind11

    does not contain a CMakeLists.txt file.


  CMake Error at CMakeLists.txt:11 (add_subdirectory):
    add_subdirectory given source "RF24/utility" which is not an existing
    directory.


  CMake Error at CMakeLists.txt:16 (pybind11_add_module):
    Unknown CMake command "pybind11_add_module".


  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-req-build-nbqjuoh7/_skbuild/linux-armv7l-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
    File "/tmp/pip-build-env-0zm_u2wh/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 588, in setup
      env = cmkr.configure(cmake_args,
    File "/tmp/pip-build-env-0zm_u2wh/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 289, in configure
      raise SKBuildError(


  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------

  Configuring Project
    Working directory:
      /tmp/pip-req-build-nbqjuoh7/_skbuild/linux-armv7l-3.9/cmake-build
    Command:
      cmake /tmp/pip-req-build-nbqjuoh7 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-req-build-nbqjuoh7/_skbuild/linux-armv7l-3.9/cmake-install/src/pyrf24 -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_VERSION_STRING:STRING=3.9.2 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/arm-linux-gnueabihf/libpython3.9.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-0zm_u2wh/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-0zm_u2wh/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DRF24_DRIVER=SPIDEV -DCMAKE_BUILD_TYPE:STRING=Release

  Traceback (most recent call last):

  An error occurred while configuring with CMake.
    Command:
      cmake /tmp/pip-req-build-nbqjuoh7 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-req-build-nbqjuoh7/_skbuild/linux-armv7l-3.9/cmake-install/src/pyrf24 -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_VERSION_STRING:STRING=3.9.2 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/arm-linux-gnueabihf/libpython3.9.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-0zm_u2wh/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-0zm_u2wh/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DRF24_DRIVER=SPIDEV -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      /tmp/pip-req-build-nbqjuoh7
    Working directory:
      /tmp/pip-req-build-nbqjuoh7/_skbuild/linux-armv7l-3.9/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for pyrf24
Failed to build pyrf24
ERROR: Could not build wheels for pyrf24 which use PEP 517 and cannot be installed directly
```

**Comment by 2bndy5** [comment]
You need to init the submodules. Use 
```
git submodule update --init
```
If it takes you should see the output of git cloning the RF24* libs and pybind11 as they are all [submodules](https://git-scm.com/docs/gitsubmodules#_description).

**Comment by 2bndy5** [comment]
you might need to use 
```
git submodule update --init --recursive
```
to ensure all submodules are checked out.

**Comment by TMRh20** [comment]
Using `git submodule update --init` worked. Thanks!

Most of the examples are checking out fine, but with the general_network_test.py I keep getting random segmentation faults. It  can take a few tries up to like 7, and only seems to happen when using RF24Mesh as a child node when sending.

**Comment by 2bndy5** [comment]
hmm try
```
cd RF24Mesh
git checkout master
```
I'm not sure if I updated it since I pushed those commits to master about initializing variables in the c'tor. That's what I had to do to fix the seg faults when using RF24Mesh. Although, a periodic seg fault is not something I experienced. I'll re-check that behavior.

**Comment by 2bndy5** [comment]
I used the "nRF Connect" app on my phone to verify _fake_ble_test.py_. Its pretty cool 🤓

**Comment by TMRh20** [comment]
I get an error on reinstall:
```
ERROR: Could not find a version that satisfies the requirement reinstall
ERROR: No matching distribution found for reinstall
```
It is a cool app. I've got it on mine as well. I tried to write some BLE code once before, but it didn't go well. :upside_down_face:

**Comment by 2bndy5** [comment]
`--force-reinstall` is supposed to be without spaces.

The little endian is the biggest hurtle in c++. That and the CRC24 needed...

**Comment by TMRh20** [comment]
Ahh yeah, that makes sense lol. I should have looked closer at the error msg... bah.

**Comment by 2bndy5** [comment]
Now I'm having trouble getting RF24Mesh to work as either master or child role. It worked when I tested it with RPi4 and my itsybitsy RP2040, but now I'm trying it with RPI4 and RPi2. So far I haven't seen a seg fault, but I did find `MSH Invalid id or type rcvd` on RPi4 as master. I have a sneaky feeling it might have something to do with conversion of char* buffer to bytearray...

**Comment by 2bndy5** [comment]
@TMRh20 I think I need more context to reproduce the seg fault. I tried the generic net test again and it is working for both master and child roles between RPi4 and RPi2 I did notice (using `-DMESH_DEBUG=ON`) that the child role's `renew_address()` takes more than 1 cycle through the net levels to connect to the master. During one of the attempts, I had to call `renew_address()` twice. However, with the debug statements on, the mesh master may take longer to respond than with the debug statements off.

I changed all the py bindings to accept buffer objects by value instead of reference. I'm not sure this will fix any seg faults since pybind11 does some implicit casting of parameters concerning pass-by-ref vs pass-by-val.

I've also improved the generic net test example so that `mesh.begin()` doesn't throw an `OSError`. This allows the user to reattempt `renew_address()`. To ensure radio hardware is responding, I have `radio.begin()` called before `mesh.begin()`.

**Comment by TMRh20** [comment]
After reinstalling on my RPi4 with your latest changes, I can't reproduce the seg fault. Tried it on my Model B Rev 2 and its working fine as well.

**Comment by 2bndy5** [comment]
I figured out a way to install this package on non-Linux OSs to make use of only the stub files (type hinting used by IDEs and static type checkers like [mypy](https://mypy.readthedocs.io/en/stable/)).
image
Unfortunately, Sphinx doesn't support reading docs from stub files, so we still have to generate the docs from a Linux machine because they are extracted from the installed pyrf24 pkg.

Executing anything in the python REPL will still yield errors like `No module named 'pyrf24.rf24'` on anything that isn't Linux, but this gets rid of a lot of errors/warnings and red squiggly underlined syntax in IDEs for developers (including us) coding on non-SoC machines. 👍🏼

**Pull request merged**
